// @generated by `cargo xtask thresholds` from conformance/sweeps/thresholds.csv — do not edit.
// Source sweep rev: sha256 682e39c1bb408e0faf10494a13cd6318db6ec03d1ac7e9066846c5f382e42f8f.
// Source series: conformance/corpus/coeff_series.jsonl, sha256 e030c23861992a2756e74059cf35a1bafa4ea071bfe5b23b0c0a4bdb97ecf773.

use super::Switch;

// Objective (max u): value 1.2088762076224056e0, derivative 1.3618440641248368e1.
pub(crate) const K_F64: Switch<f64, 8> = Switch::first(
    f64::from_bits(0x3ff0_0000_0000_0000), // θ² < 1e0
    &SWEPT_K_F64,
);

// Objective (max u): value 2.822622370921484e0, derivative 2.579516907180818e1.
pub(crate) const A_F64: Switch<f64, 8> = Switch::first(
    f64::from_bits(0x3fe7_260b_83e2_4841), // θ² < 7.233941627366748e-1
    &SWEPT_A_F64,
);

// Objective (max u): value 2.6101666247318667e0, derivative 6.3537892681326746e1.
pub(crate) const B_F64: Switch<f64, 8> = Switch::first(
    f64::from_bits(0x3fee_de82_0ba7_3310), // θ² < 9.646616199111993e-1
    &SWEPT_B_F64,
);

// Objective (max u): value 2.1181591514984923e1, derivative 7.3955289560728515e3.
pub(crate) const C_F64: Switch<f64, 8> = Switch::first(
    f64::from_bits(0x3fe1_feb3_3c1c_381e), // θ² < 5.623413251903491e-1
    &SWEPT_C_F64,
);

// Objective (max u): value 1.8509383104643042e1, derivative 8.307295036368967e2.
pub(crate) const D_F64: Switch<f64, 8> = Switch::first(
    f64::from_bits(0x3ff0_0000_0000_0000), // θ² < 1e0
    &SWEPT_D_F64,
);

// Objective (max u): value 1.5588061416067464e2, derivative 8.687771882940042e3.
pub(crate) const E_F64: Switch<f64, 7> = Switch::first(
    f64::from_bits(0x3fee_de82_0ba7_3310), // θ² < 9.646616199111993e-1
    &SWEPT_E_F64,
);

// Objective (max u): value 8.440420878958678e-1, derivative 1.9535556445629474e0.
pub(crate) const COS_HALF_F64: Switch<f64, 2> = Switch::first(
    f64::from_bits(0x3cf9_535a_a429_6d58), // θ² < 5.623413251903491e-15
    &SWEPT_COS_HALF_F64,
);

// Objective (max u): value 2.282754876639517e0, derivative 2.6025843819341594e2.
pub(crate) const R_F64: Switch<f64, 8> = Switch::first(
    f64::from_bits(0x3f86_020a_364b_1284), // n²/w² < 1.0746078283213174e-2
    &SWEPT_R_F64,
);

// Objective (max u): value 1.1396368061293227e0, derivative 1.2126836136234648e1.
pub(crate) const K_F32: Switch<f32, 5> = Switch::first(
    f32::from_bits(0x3f80_0000), // θ² < 1e0
    &SWEPT_K_F32,
);

// Objective (max u): value 2.60480623229529e0, derivative 1.2715345525062054e1.
pub(crate) const A_F32: Switch<f32, 5> = Switch::first(
    f32::from_bits(0x3f80_0000), // θ² < 1e0
    &SWEPT_A_F32,
);

// Objective (max u): value 2.963841020701417e0, derivative 5.9242390058740725e1.
pub(crate) const B_F32: Switch<f32, 5> = Switch::first(
    f32::from_bits(0x3f80_0000), // θ² < 1e0
    &SWEPT_B_F32,
);

// Objective (max u): value 2.374959546508359e1, derivative 1.612254753089976e3.
pub(crate) const C_F32: Switch<f32, 4> = Switch::first(
    f32::from_bits(0x3f80_0000), // θ² < 1e0
    &SWEPT_C_F32,
);

// Objective (max u): value 1.9849217762953725e1, derivative 1.0449845627160194e3.
pub(crate) const D_F32: Switch<f32, 4> = Switch::first(
    f32::from_bits(0x3f80_0000), // θ² < 1e0
    &SWEPT_D_F32,
);

// Objective (max u): value 7.812286714685952e1, derivative 4.4285331421784695e3.
pub(crate) const E_F32: Switch<f32, 4> = Switch::first(
    f32::from_bits(0x3f80_0000), // θ² < 1e0
    &SWEPT_E_F32,
);

// Objective (max u): value 8.170483788453252e-1, derivative 1.8676548828902029e0.
pub(crate) const COS_HALF_F32: Switch<f32, 2> = Switch::first(
    f32::from_bits(0x3631_472c), // θ² < 2.6416483e-6
    &SWEPT_COS_HALF_F32,
);

// Objective (max u): value 2.0719517848627165e0, derivative 2.665869661957877e1.
pub(crate) const R_F32: Switch<f32, 8> = Switch::first(
    f32::from_bits(0x3e12_bd91), // n²/w² < 1.4330126e-1
    &SWEPT_R_F32,
);

// The series `helicoid::__sweep` measures: the first 8 terms of each row, the exact
// rational rounded once at its precision. A function of the corpus alone.
pub(crate) const SWEPT_K_F64: [f64; 8] = [
    5e-1,
    -2.0833333333333332e-2,
    2.6041666666666666e-4,
    -1.5500992063492063e-6,
    5.382288910934745e-9,
    -1.2232474797578965e-11,
    1.9603324996120133e-14,
    -2.333729166204778e-17,
];

pub(crate) const SWEPT_A_F64: [f64; 8] = [
    5e-1,
    -4.1666666666666664e-2,
    1.388888888888889e-3,
    -2.48015873015873e-5,
    2.755731922398589e-7,
    -2.08767569878681e-9,
    1.1470745597729725e-11,
    -4.779477332387385e-14,
];

pub(crate) const SWEPT_B_F64: [f64; 8] = [
    1.6666666666666666e-1,
    -8.333333333333333e-3,
    1.984126984126984e-4,
    -2.7557319223985893e-6,
    2.505210838544172e-8,
    -1.6059043836821613e-10,
    7.647163731819816e-13,
    -2.8114572543455206e-15,
];

pub(crate) const SWEPT_C_F64: [f64; 8] = [
    8.333333333333333e-2,
    1.388888888888889e-3,
    3.306878306878307e-5,
    8.267195767195768e-7,
    2.08767569878681e-8,
    5.284190138687493e-10,
    1.3382536530684679e-11,
    3.3896802963225827e-13,
];

pub(crate) const SWEPT_D_F64: [f64; 8] = [
    4.1666666666666664e-2,
    -1.388888888888889e-3,
    2.48015873015873e-5,
    -2.755731922398589e-7,
    2.08767569878681e-9,
    -1.1470745597729725e-11,
    4.779477332387385e-14,
    -1.5619206968586225e-16,
];

pub(crate) const SWEPT_E_F64: [f64; 8] = [
    8.333333333333333e-3,
    -3.968253968253968e-4,
    8.267195767195768e-6,
    -1.0020843354176688e-7,
    8.029521918410807e-10,
    -4.58829823909189e-12,
    1.9680200780418645e-14,
    -6.576508197299464e-17,
];

pub(crate) const SWEPT_COS_HALF_F64: [f64; 8] = [
    1e0,
    -1.25e-1,
    2.6041666666666665e-3,
    -2.170138888888889e-5,
    9.68812003968254e-8,
    -2.691144455467372e-10,
    5.096864498991235e-13,
    -7.001187498614334e-16,
];

pub(crate) const SWEPT_R_F64: [f64; 8] = [
    1e0,
    -3.333333333333333e-1,
    2e-1,
    -1.4285714285714285e-1,
    1.111111111111111e-1,
    -9.090909090909091e-2,
    7.692307692307693e-2,
    -6.666666666666667e-2,
];

pub(crate) const SWEPT_K_F32: [f32; 8] = [
    5e-1,
    -2.0833334e-2,
    2.6041668e-4,
    -1.5500992e-6,
    5.382289e-9,
    -1.2232475e-11,
    1.9603326e-14,
    -2.3337291e-17,
];

pub(crate) const SWEPT_A_F32: [f32; 8] = [
    5e-1,
    -4.1666668e-2,
    1.3888889e-3,
    -2.4801588e-5,
    2.755732e-7,
    -2.0876756e-9,
    1.1470745e-11,
    -4.7794773e-14,
];

pub(crate) const SWEPT_B_F32: [f32; 8] = [
    1.6666667e-1,
    -8.333334e-3,
    1.984127e-4,
    -2.7557319e-6,
    2.5052108e-8,
    -1.6059044e-10,
    7.6471636e-13,
    -2.8114574e-15,
];

pub(crate) const SWEPT_C_F32: [f32; 8] = [
    8.3333336e-2,
    1.3888889e-3,
    3.3068784e-5,
    8.267196e-7,
    2.0876756e-8,
    5.2841903e-10,
    1.3382536e-11,
    3.3896803e-13,
];

pub(crate) const SWEPT_D_F32: [f32; 8] = [
    4.1666668e-2,
    -1.3888889e-3,
    2.4801588e-5,
    -2.755732e-7,
    2.0876756e-9,
    -1.1470745e-11,
    4.7794773e-14,
    -1.5619207e-16,
];

pub(crate) const SWEPT_E_F32: [f32; 8] = [
    8.333334e-3,
    -3.968254e-4,
    8.267196e-6,
    -1.0020843e-7,
    8.029522e-10,
    -4.588298e-12,
    1.96802e-14,
    -6.576508e-17,
];

pub(crate) const SWEPT_COS_HALF_F32: [f32; 8] = [
    1e0,
    -1.25e-1,
    2.6041667e-3,
    -2.170139e-5,
    9.68812e-8,
    -2.6911445e-10,
    5.096864e-13,
    -7.0011874e-16,
];

pub(crate) const SWEPT_R_F32: [f32; 8] = [
    1e0,
    -3.3333334e-1,
    2e-1,
    -1.4285715e-1,
    1.1111111e-1,
    -9.090909e-2,
    7.692308e-2,
    -6.666667e-2,
];
