// @generated by `cargo xtask thresholds` from conformance/sweeps/thresholds.csv — do not edit.
// Source sweep rev: sha256 bd9418e8c328659e28f6dca2059d0f3862d1a77af9a34bb45d9412a42d0f4700.
// Source series: conformance/corpus/coeff_series.jsonl, sha256 e030c23861992a2756e74059cf35a1bafa4ea071bfe5b23b0c0a4bdb97ecf773.

use super::Switch;

// Objective (max u): value 1.0440879650426402e0, derivative 2.6896926681097066e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: domain.
pub(crate) const K_F64: Switch<f64, 11> = Switch::first(
    f64::from_bits(0x4023_4b11_4748_7fea), // θ² < 9.646616199111993e0
    &SWEPT_K_F64,
);

// Objective (max u): value 2.223959655638656e0, derivative 3.4078383457717867e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: none.
pub(crate) const A_F64: Switch<f64, 13> = Switch::first(
    f64::from_bits(0x4020_b50e_65c5_be18), // θ² < 8.353625469578262e0
    &SWEPT_A_F64,
);

// Objective (max u): value 1.7142989082563274e0, derivative 5.668554842355219e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: domain.
pub(crate) const B_F64: Switch<f64, 13> = Switch::first(
    f64::from_bits(0x4023_4b11_4748_7fea), // θ² < 9.646616199111993e0
    &SWEPT_B_F64,
);

// Objective (max u): value 3.3926626301476173e0, derivative 9.447772765454434e1.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: terms.
pub(crate) const C_F64: Switch<f64, 16> = Switch::first(
    f64::from_bits(0x400f_64bd_999f_e9ec), // θ² < 3.9241897584845358e0
    &SWEPT_C_F64,
);

// Objective (max u): value 1.8725213481387972e0, derivative 7.902832186623222e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: domain.
pub(crate) const D_F64: Switch<f64, 13> = Switch::first(
    f64::from_bits(0x4023_4b11_4748_7fea), // θ² < 9.646616199111993e0
    &SWEPT_D_F64,
);

// Objective (max u): value 2.8357053165959805e0, derivative 1.9872142825544316e1.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: none.
pub(crate) const E_F64: Switch<f64, 12> = Switch::first(
    f64::from_bits(0x4021_f428_7a6e_0653), // θ² < 8.976871324473143e0
    &SWEPT_E_F64,
);

// Objective (max u): value 1.7791082766434974e0, derivative 1.7469374133117896e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: none.
pub(crate) const COS_HALF_F64: Switch<f64, 10> = Switch::first(
    f64::from_bits(0x4014_ee95_3b2f_4f99), // θ² < 5.232991146814947e0
    &SWEPT_COS_HALF_F64,
);

// Objective (max u): value 2.282754876639517e0, derivative 3.663742854570427e1.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: none.
pub(crate) const R_F64: Switch<f64, 15> = Switch::first(
    f64::from_bits(0x3fb6_fb15_1797_1255), // n²/w² < 8.976871324473142e-2
    &SWEPT_R_F64,
);

// Objective (max u): value 1.1549701491341435e0, derivative 1.9942779455613127e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: domain.
pub(crate) const K_F32: Switch<f32, 7> = Switch::first(
    f32::from_bits(0x411a_588a), // θ² < 9.646616e0
    &SWEPT_K_F32,
);

// Objective (max u): value 2.0579854310208265e0, derivative 2.692028636086276e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: domain.
pub(crate) const A_F32: Switch<f32, 9> = Switch::first(
    f32::from_bits(0x411a_588a), // θ² < 9.646616e0
    &SWEPT_A_F32,
);

// Objective (max u): value 1.301984579383122e0, derivative 7.765782273480911e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: none.
pub(crate) const B_F32: Switch<f32, 7> = Switch::first(
    f32::from_bits(0x40f8_c1be), // θ² < 7.77365e0
    &SWEPT_B_F32,
);

// Objective (max u): value 1.2484877334573738e0, derivative 3.9265516050743e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: none.
pub(crate) const C_F32: Switch<f32, 13> = Switch::first(
    f32::from_bits(0x410f_a144), // θ² < 8.9768715e0
    &SWEPT_C_F32,
);

// Objective (max u): value 1.8762573817186103e0, derivative 1.2955271511545845e1.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: domain.
pub(crate) const D_F32: Switch<f32, 7> = Switch::first(
    f32::from_bits(0x411a_588a), // θ² < 9.646616e0
    &SWEPT_D_F32,
);

// Objective (max u): value 2.538165684583726e0, derivative 1.564673950333894e1.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: none.
pub(crate) const E_F32: Switch<f32, 7> = Switch::first(
    f32::from_bits(0x410f_a144), // θ² < 8.9768715e0
    &SWEPT_E_F32,
);

// Objective (max u): value 1.2195768246443892e0, derivative 1.5413124165129917e0.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: none.
pub(crate) const COS_HALF_F32: Switch<f32, 6> = Switch::first(
    f32::from_bits(0x4091_02bc), // θ² < 4.531584e0
    &SWEPT_COS_HALF_F32,
);

// Objective (max u): value 2.3645725053943423e0, derivative 1.0414390269290626e1.
// Feasibility: grid [1e-16, 1e1] of 64 per decade searched below π², terms <= 16; binding: none.
pub(crate) const R_F32: Switch<f32, 15> = Switch::first(
    f32::from_bits(0x3ec1_d181), // n²/w² < 3.785515e-1
    &SWEPT_R_F32,
);

// The series `helicoid::__sweep` measures: the first 16 terms of each row, the exact
// rational rounded once at its precision. A function of the corpus alone.
pub(crate) const SWEPT_K_F64: [f64; 16] = [
    5e-1,
    -2.0833333333333332e-2,
    2.6041666666666666e-4,
    -1.5500992063492063e-6,
    5.382288910934745e-9,
    -1.2232474797578965e-11,
    1.9603324996120133e-14,
    -2.333729166204778e-17,
    2.1449716601146855e-20,
    -1.5679617398499164e-23,
    9.333105594344741e-27,
    -4.6112181790240814e-30,
    1.9213409079267006e-33,
    -6.842382150736113e-37,
    2.106644750842399e-40,
    -5.66302352376989e-44,
];

pub(crate) const SWEPT_A_F64: [f64; 16] = [
    5e-1,
    -4.1666666666666664e-2,
    1.388888888888889e-3,
    -2.48015873015873e-5,
    2.755731922398589e-7,
    -2.08767569878681e-9,
    1.1470745597729725e-11,
    -4.779477332387385e-14,
    1.5619206968586225e-16,
    -4.110317623312165e-19,
    8.896791392450574e-22,
    -1.6117375710961184e-24,
    2.4795962632247976e-27,
    -3.279889237069838e-30,
    3.7699876288159054e-33,
    -3.8003907548547434e-36,
];

pub(crate) const SWEPT_B_F64: [f64; 16] = [
    1.6666666666666666e-1,
    -8.333333333333333e-3,
    1.984126984126984e-4,
    -2.7557319223985893e-6,
    2.505210838544172e-8,
    -1.6059043836821613e-10,
    7.647163731819816e-13,
    -2.8114572543455206e-15,
    8.22063524662433e-18,
    -1.9572941063391263e-20,
    3.868170170630684e-23,
    -6.446950284384474e-26,
    9.183689863795546e-29,
    -1.1309962886447716e-31,
    1.216125041553518e-34,
    -1.151633562077195e-37,
];

pub(crate) const SWEPT_C_F64: [f64; 16] = [
    8.333333333333333e-2,
    1.388888888888889e-3,
    3.306878306878307e-5,
    8.267195767195768e-7,
    2.08767569878681e-8,
    5.284190138687493e-10,
    1.3382536530684679e-11,
    3.3896802963225827e-13,
    8.586062056277845e-15,
    2.174868698558062e-16,
    5.5090028283602295e-18,
    1.3954464685812522e-19,
    3.534707039629467e-21,
    8.953517427037546e-23,
    2.267952452337683e-24,
    5.744790668872202e-26,
];

pub(crate) const SWEPT_D_F64: [f64; 16] = [
    4.1666666666666664e-2,
    -1.388888888888889e-3,
    2.48015873015873e-5,
    -2.755731922398589e-7,
    2.08767569878681e-9,
    -1.1470745597729725e-11,
    4.779477332387385e-14,
    -1.5619206968586225e-16,
    4.110317623312165e-19,
    -8.896791392450574e-22,
    1.6117375710961184e-24,
    -2.4795962632247976e-27,
    3.279889237069838e-30,
    -3.7699876288159054e-33,
    3.8003907548547434e-36,
    -3.387157535521162e-39,
];

pub(crate) const SWEPT_E_F64: [f64; 16] = [
    8.333333333333333e-3,
    -3.968253968253968e-4,
    8.267195767195768e-6,
    -1.0020843354176688e-7,
    8.029521918410807e-10,
    -4.58829823909189e-12,
    1.9680200780418645e-14,
    -6.576508197299464e-17,
    1.7615646957052136e-19,
    -3.868170170630684e-22,
    7.091645312822921e-25,
    -1.1020427836554655e-27,
    1.4702951752382032e-30,
    -1.7025750581749252e-33,
    1.7274503431157927e-36,
    -1.5484148733811025e-39,
];

pub(crate) const SWEPT_COS_HALF_F64: [f64; 16] = [
    1e0,
    -1.25e-1,
    2.6041666666666665e-3,
    -2.170138888888889e-5,
    9.68812003968254e-8,
    -2.691144455467372e-10,
    5.096864498991235e-13,
    -7.001187498614334e-16,
    7.292903644389931e-19,
    -5.958254611429682e-22,
    3.919904349624791e-25,
    -2.1211603623510776e-28,
    9.606704539633503e-32,
    -3.694886361397501e-35,
    1.2218539554885916e-38,
    -3.511074584737332e-42,
];

pub(crate) const SWEPT_R_F64: [f64; 16] = [
    1e0,
    -3.333333333333333e-1,
    2e-1,
    -1.4285714285714285e-1,
    1.111111111111111e-1,
    -9.090909090909091e-2,
    7.692307692307693e-2,
    -6.666666666666667e-2,
    5.8823529411764705e-2,
    -5.263157894736842e-2,
    4.7619047619047616e-2,
    -4.3478260869565216e-2,
    4e-2,
    -3.7037037037037035e-2,
    3.4482758620689655e-2,
    -3.225806451612903e-2,
];

pub(crate) const SWEPT_K_F32: [f32; 16] = [
    5e-1,
    -2.0833334e-2,
    2.6041668e-4,
    -1.5500992e-6,
    5.382289e-9,
    -1.2232475e-11,
    1.9603326e-14,
    -2.3337291e-17,
    2.1449717e-20,
    -1.5679617e-23,
    9.333106e-27,
    -4.6112183e-30,
    1.921341e-33,
    -6.842382e-37,
    2.10664e-40,
    -5.6e-44,
];

pub(crate) const SWEPT_A_F32: [f32; 16] = [
    5e-1,
    -4.1666668e-2,
    1.3888889e-3,
    -2.4801588e-5,
    2.755732e-7,
    -2.0876756e-9,
    1.1470745e-11,
    -4.7794773e-14,
    1.5619207e-16,
    -4.1103176e-19,
    8.896791e-22,
    -1.6117376e-24,
    2.4795963e-27,
    -3.279889e-30,
    3.7699878e-33,
    -3.8003907e-36,
];

pub(crate) const SWEPT_B_F32: [f32; 16] = [
    1.6666667e-1,
    -8.333334e-3,
    1.984127e-4,
    -2.7557319e-6,
    2.5052108e-8,
    -1.6059044e-10,
    7.6471636e-13,
    -2.8114574e-15,
    8.220635e-18,
    -1.9572942e-20,
    3.8681703e-23,
    -6.4469503e-26,
    9.18369e-29,
    -1.1309962e-31,
    1.216125e-34,
    -1.1516336e-37,
];

pub(crate) const SWEPT_C_F32: [f32; 16] = [
    8.3333336e-2,
    1.3888889e-3,
    3.3068784e-5,
    8.267196e-7,
    2.0876756e-8,
    5.2841903e-10,
    1.3382536e-11,
    3.3896803e-13,
    8.586062e-15,
    2.1748687e-16,
    5.509003e-18,
    1.3954465e-19,
    3.534707e-21,
    8.9535176e-23,
    2.2679524e-24,
    5.744791e-26,
];

pub(crate) const SWEPT_D_F32: [f32; 16] = [
    4.1666668e-2,
    -1.3888889e-3,
    2.4801588e-5,
    -2.755732e-7,
    2.0876756e-9,
    -1.1470745e-11,
    4.7794773e-14,
    -1.5619207e-16,
    4.1103176e-19,
    -8.896791e-22,
    1.6117376e-24,
    -2.4795963e-27,
    3.279889e-30,
    -3.7699878e-33,
    3.8003907e-36,
    -3.387157e-39,
];

pub(crate) const SWEPT_E_F32: [f32; 16] = [
    8.333334e-3,
    -3.968254e-4,
    8.267196e-6,
    -1.0020843e-7,
    8.029522e-10,
    -4.588298e-12,
    1.96802e-14,
    -6.576508e-17,
    1.7615647e-19,
    -3.8681702e-22,
    7.091645e-25,
    -1.1020428e-27,
    1.4702952e-30,
    -1.702575e-33,
    1.7274503e-36,
    -1.548415e-39,
];

pub(crate) const SWEPT_COS_HALF_F32: [f32; 16] = [
    1e0,
    -1.25e-1,
    2.6041667e-3,
    -2.170139e-5,
    9.68812e-8,
    -2.6911445e-10,
    5.096864e-13,
    -7.0011874e-16,
    7.2929035e-19,
    -5.9582546e-22,
    3.9199043e-25,
    -2.1211603e-28,
    9.6067047e-32,
    -3.6948864e-35,
    1.2218539e-38,
    -3.512e-42,
];

pub(crate) const SWEPT_R_F32: [f32; 16] = [
    1e0,
    -3.3333334e-1,
    2e-1,
    -1.4285715e-1,
    1.1111111e-1,
    -9.090909e-2,
    7.692308e-2,
    -6.666667e-2,
    5.882353e-2,
    -5.263158e-2,
    4.761905e-2,
    -4.347826e-2,
    4e-2,
    -3.7037037e-2,
    3.448276e-2,
    -3.2258064e-2,
];
