//! `docs/evidence/ENVELOPE.md` (`docs/PHASE1.md` §8): per function and stratum, the candidate's max
//! and p99 and the best oracle with its version. A function of the rows only: no revision, no
//! time, so `--bless` twice writes the same bytes, and `--check` can compare.

use std::fmt::Write;

use crate::conformance::report::{precision_name, Row};

use super::bars::Index;
use super::rows::{Key, Subject};

/// Where the page is, relative to the repository root; `cargo xtask lint` registers it.
pub(super) const PATH: &str = "docs/evidence/ENVELOPE.md";

const HEADER: &str = "<!-- @generated by `cargo xtask envelope` from conformance/results and \
conformance/baseline — do not edit. -->";

/// The page for `candidate` (`name` when it has no rows) against `oracles`, plus the exceptions
/// `0046` item 5 asks the page to print: "the page a reader trusts says what it is not claiming".
///
/// The exceptions table's last three columns are the oracle's name, its maximum and the margin —
/// the same convention as the main table's last three, so [`candidate_view`] drops them and
/// `--check` does not compare a figure measured on a runner's own `libm` (EA.13(d)). The record
/// and the reason are *before* the cut and are compared, because those are what must not drift.
pub(super) fn page(
    name: &str,
    candidate: Option<&Subject>,
    oracles: &[Subject],
    excepted: &[super::bars::Excepted],
) -> String {
    let mut out = format!("{HEADER}\n\n# The envelope\n\n");
    let Some(c) = candidate else {
        let _ = writeln!(
            out,
            "Nothing is compared yet: no result rows exist for the candidate `{name}` (its in-process \
             subject is Phase 3, `PHASE3.md` §10), so no maximum stands against an oracle's and no \
             baseline is blessed. `just envelope --bless` rewrites this page."
        );
        return out;
    };
    let versions: Vec<String> = oracles
        .iter()
        .map(|o| format!("`{}` ({})", o.name, o.version))
        .collect();
    let _ = write!(
        out,
        "Candidate `{}` ({}); oracles {}.\n\n\
         Per function, stratum and precision: the largest forward error over the stratum's records \
         in units of `u`, its p99 (nearest rank), and the oracle with the smallest maximum. The bars \
         (`PHASE1.md` §8) are on the max: domination (at most the best oracle's, ties pass) and \
         no-regress (at most the committed baseline's, exact). A dash is a stratum no oracle scored \
         or one nothing is scored in. The last three columns are the oracle runners', on their own \
         `libm`, which `--check` does not compare (`error-analysis.md` EA.13(d)).\n\n\
         | function | stratum | precision | n | max u | p99 u | best oracle | version | oracle max u |\n\
         |---|---|---|---|---|---|---|---|---|\n",
        c.name,
        c.version,
        versions.join(", ")
    );
    let index = Index::new(oracles);
    for r in &c.rows {
        let (max, p99) = match (r.nonfinite, r.max_u.is_finite()) {
            (0, true) => (format!("{:.4e}", r.max_u), format!("{:.4e}", r.p99_u)),
            (0, false) => ("—".into(), "—".into()),
            (k, _) => (format!("{k} non-finite"), "—".into()),
        };
        let best = index.best(&Key::of(r), r.n, &mut Vec::new());
        let (name, version, theirs) =
            best.map_or(("—".into(), "—".into(), "—".into()), |(o, m)| {
                (
                    format!("`{}`", o.name),
                    o.version.clone(),
                    format!("{m:.4e}"),
                )
            });
        let Row {
            fn_id,
            stratum,
            precision,
            n,
            ..
        } = r;
        let precision = precision_name(*precision);
        let _ = writeln!(out, "| `{fn_id}` | `{stratum}` | {precision} | {n} | {max} | {p99} | {name} | {version} | {theirs} |");
    }
    out += &exceptions_section(excepted);
    out
}

/// The strata an oracle wins that a record explains, or a line saying there are none.
///
/// `0046` item 2: an exception changes the domination bar and nothing else, so each of these
/// maxima is in the baseline and judged by no-regress like every other. The section says so, in
/// case a reader takes "excepted" for "excused".
fn exceptions_section(excepted: &[super::bars::Excepted]) -> String {
    let mut out = String::from("\n## Exceptions\n\n");
    if excepted.is_empty() {
        out += "None: every paired stratum is dominated or unpaired.\n";
        return out;
    }
    let _ = write!(
        out,
        "{} strata an oracle wins, each explained by the `ready` record it cites in \
         `{}`. **This is not an excuse:** the exception moves the domination bar only, so each \
         maximum below is still written to the baseline and still has to not regress — an \
         excepted stratum is watched more closely than a dominated one. `cargo xtask lint` fails \
         a row whose record is missing or is a draft, and `just envelope` fails a row whose \
         stratum turns out to be dominated after all.\n\n\
         | function | stratum | precision | max u | record | reason | best oracle | oracle max u \
         | margin u |\n|---|---|---|---|---|---|---|---|---|\n",
        excepted.len(),
        super::exceptions::PATH
    );
    for e in excepted {
        let (fn_id, rest) = e.key.split_once('/').unwrap_or((e.key.as_str(), ""));
        let (stratum, precision) = rest.rsplit_once('/').unwrap_or((rest, ""));
        let _ = writeln!(
            out,
            "| `{fn_id}` | `{stratum}` | {precision} | {:.4e} | [`{}`](../decisions) | {} | \
             `{}` | {:.4e} | {:.4e} |",
            e.candidate,
            e.record,
            e.reason,
            e.oracle_name,
            e.oracle,
            e.candidate - e.oracle
        );
    }
    out
}

/// `page` without the columns the oracle runners fill in (the best oracle, its version and its
/// maximum): they are measured on the host's `libm`, which D16 does not cover, so one source can
/// print another best oracle or another fifth digit on another runner image. `--check` compares
/// this view; `--bless` writes the whole page.
pub(super) fn candidate_view(page: &str) -> String {
    let mut out = String::new();
    for line in page.lines() {
        match line.starts_with("| `") {
            true => out += &line.splitn(8, '|').take(7).collect::<Vec<_>>().join("|"),
            false => out += line,
        }
        out.push('\n');
    }
    out
}

/// Why `committed` is not `fresh`: the first line that differs, or that one is a prefix.
pub(super) fn first_difference(committed: &str, fresh: &str) -> Option<String> {
    if committed == fresh {
        return None;
    }
    let mut lines = committed.lines().zip(fresh.lines()).enumerate();
    Some(lines.find(|(_, (a, b))| a != b).map_or_else(
        || "one is a prefix of the other".to_string(),
        |(i, (a, b))| format!("line {}: committed `{a}`, fresh `{b}`", i + 1),
    ))
}

#[cfg(test)]
mod tests {
    use super::super::rows::testing::row;
    use super::*;

    fn subject(name: &str, rows: Vec<Row>) -> Subject {
        Subject {
            name: name.into(),
            version: format!("{name}@1"),
            rows,
        }
    }

    #[test]
    fn the_page_names_the_best_oracle_and_its_version_per_stratum() {
        let cand = subject(
            "c",
            vec![
                row("c", "f", "a", 1.5),
                row("c", "f", "b", 2.0),
                row("c", "g", "a", 3.0),
            ],
        );
        let slow = subject(
            "slow",
            vec![row("slow", "f", "a", 9.0), row("slow", "f", "b", 4.0)],
        );
        let fast = subject(
            "fast",
            vec![row("fast", "f", "a", 2.5), row("fast", "g", "z", 1.0)],
        );
        let text = page("c", Some(&cand), &[slow, fast], &[]);
        let rows: Vec<&str> = text.lines().filter(|l| l.starts_with("| `")).collect();
        assert_eq!(
            rows,
            [
                "| `f` | `a` | f64 | 64 | 1.5000e0 | 7.5000e-1 | `fast` | fast@1 | 2.5000e0 |",
                "| `f` | `b` | f64 | 64 | 2.0000e0 | 1.0000e0 | `slow` | slow@1 | 4.0000e0 |",
                "| `g` | `a` | f64 | 64 | 3.0000e0 | 1.5000e0 | — | — | — |",
            ]
        );
        assert!(text.contains("Candidate `c` (c@1); oracles `slow` (slow@1), `fast` (fast@1)."));
    }

    #[test]
    fn a_first_of_equal_best_oracles_and_the_precision_are_named_on_the_page() {
        let f32_row = Row {
            precision: helicoid_linalg::Precision::F32,
            ..row("c", "f", "a", 1.0)
        };
        let cand = subject("c", vec![row("c", "f", "a", 1.0), f32_row]);
        let (first, second) = (
            subject("x", vec![row("x", "f", "a", 2.0)]),
            subject("y", vec![row("y", "f", "a", 2.0)]),
        );
        let text = page("c", Some(&cand), &[first, second], &[]);
        let rows: Vec<&str> = text.lines().filter(|l| l.starts_with("| `")).collect();
        assert_eq!(
            rows,
            [
                "| `f` | `a` | f64 | 64 | 1.0000e0 | 5.0000e-1 | `x` | x@1 | 2.0000e0 |",
                "| `f` | `a` | f32 | 64 | 1.0000e0 | 5.0000e-1 | — | — | — |",
            ]
        );
    }

    #[test]
    fn the_checked_view_keeps_the_candidate_columns_and_drops_the_oracle_ones() {
        let cand = subject("c", vec![row("c", "f", "a", 1.5), row("c", "f", "b", 2.0)]);
        let with = |cand: &Subject, mx: f64, my: f64| {
            let of = |n: &str, m: f64| subject(n, vec![row(n, "f", "a", m), row(n, "f", "b", m)]);
            page("c", Some(cand), &[of("x", mx), of("y", my)], &[])
        };
        // Another best oracle and another fifth digit: the same view; another candidate max: not.
        let (a, b) = (with(&cand, 3.5625, 4.0), with(&cand, 4.0, 2.6875));
        assert_ne!(a, b);
        assert_eq!(candidate_view(&a), candidate_view(&b));
        let other = subject("c", vec![row("c", "f", "a", 1.5), row("c", "f", "b", 2.5)]);
        assert_ne!(
            candidate_view(&a),
            candidate_view(&with(&other, 3.5625, 4.0))
        );
        let view = candidate_view(&a);
        assert!(view.contains("| `f` | `a` | f64 | 64 | 1.5000e0 | 7.5000e-1 \n"));
        assert!(!view.contains("| `x` |") && view.contains("| best oracle | version |"));
    }

    #[test]
    fn a_stratum_nothing_is_scored_in_is_a_dash_and_a_non_finite_one_says_so() {
        let unscored = Row {
            max_u: f64::NAN,
            p99_u: f64::NAN,
            ..row("c", "f", "u", 0.0)
        };
        let bad = Row {
            max_u: f64::NAN,
            p99_u: f64::NAN,
            nonfinite: 2,
            ..row("c", "f", "n", 0.0)
        };
        let text = page("c", Some(&subject("c", vec![unscored, bad])), &[], &[]);
        assert!(text.contains("| `f` | `u` | f64 | 64 | — | — | — | — | — |"));
        assert!(text.contains("| `f` | `n` | f64 | 64 | 2 non-finite | — | — | — | — |"));
    }

    #[test]
    fn without_candidate_rows_the_page_says_nothing_is_compared_and_it_is_registered_output() {
        let text = page("helicoid", None, &[], &[]);
        assert!(text.starts_with(HEADER) && text.contains("for the candidate `helicoid`"));
        assert_eq!(
            text,
            page(
                "helicoid",
                None,
                &[subject("o", vec![row("o", "f", "a", 1.0)])],
                &[]
            )
        );
        // The registry parses this header as the output of `envelope`, and finds the file.
        let file = crate::lint::File {
            path: PATH.into(),
            text,
        };
        let violations = crate::lint::check_all(&[file]);
        assert!(violations.iter().all(|v| v.path != PATH), "{violations:?}");
    }

    #[test]
    fn the_first_difference_names_the_line() {
        assert_eq!(first_difference("a\nb\n", "a\nb\n"), None);
        let d = first_difference("a\nb\n", "a\nc\n").unwrap_or_default();
        assert_eq!(d, "line 2: committed `b`, fresh `c`");
        assert!(first_difference("a\n", "a\nb\n").is_some_and(|d| d.contains("prefix")));
    }
}
