// @generated by `cargo xtask thresholds` from conformance/sweeps/thresholds.csv — do not edit.
// Source sweep rev: sha256 94bc8263cf5ec140810053a24e25e580df3c9e5e6ee1a6787126021276c0e538.
// Source series: conformance/corpus/coeff_series.jsonl, sha256 e030c23861992a2756e74059cf35a1bafa4ea071bfe5b23b0c0a4bdb97ecf773.

use super::switch::Switch;

// Objective (max u): value 1.2088762076224056e0, derivative 1.3618440641248368e1.
pub(crate) const K_F64: Switch<f64, 8> = Switch {
    below: f64::from_bits(0x3ff0_0000_0000_0000), // θ² < 1e0
    series: [
        5e-1,
        -2.0833333333333332e-2,
        2.6041666666666666e-4,
        -1.5500992063492063e-6,
        5.382288910934745e-9,
        -1.2232474797578965e-11,
        1.9603324996120133e-14,
        -2.333729166204778e-17,
    ],
};

// Objective (max u): value 2.822622370921484e0, derivative 2.579516907180818e1.
pub(crate) const A_F64: Switch<f64, 8> = Switch {
    below: f64::from_bits(0x3fe7_260b_83e2_4841), // θ² < 7.233941627366748e-1
    series: [
        5e-1,
        -4.1666666666666664e-2,
        1.388888888888889e-3,
        -2.48015873015873e-5,
        2.755731922398589e-7,
        -2.08767569878681e-9,
        1.1470745597729725e-11,
        -4.779477332387385e-14,
    ],
};

// Objective (max u): value 2.6101666247318667e0, derivative 6.3537892681326746e1.
pub(crate) const B_F64: Switch<f64, 8> = Switch {
    below: f64::from_bits(0x3fee_de82_0ba7_3310), // θ² < 9.646616199111993e-1
    series: [
        1.6666666666666666e-1,
        -8.333333333333333e-3,
        1.984126984126984e-4,
        -2.7557319223985893e-6,
        2.505210838544172e-8,
        -1.6059043836821613e-10,
        7.647163731819816e-13,
        -2.8114572543455206e-15,
    ],
};

// Objective (max u): value 2.1181591514984923e1, derivative 7.3955289560728515e3.
pub(crate) const C_F64: Switch<f64, 8> = Switch {
    below: f64::from_bits(0x3fe1_feb3_3c1c_381e), // θ² < 5.623413251903491e-1
    series: [
        8.333333333333333e-2,
        1.388888888888889e-3,
        3.306878306878307e-5,
        8.267195767195768e-7,
        2.08767569878681e-8,
        5.284190138687493e-10,
        1.3382536530684679e-11,
        3.3896802963225827e-13,
    ],
};

// Objective (max u): value 1.8509383104643042e1, derivative 8.307295036368967e2.
pub(crate) const D_F64: Switch<f64, 8> = Switch {
    below: f64::from_bits(0x3ff0_0000_0000_0000), // θ² < 1e0
    series: [
        4.1666666666666664e-2,
        -1.388888888888889e-3,
        2.48015873015873e-5,
        -2.755731922398589e-7,
        2.08767569878681e-9,
        -1.1470745597729725e-11,
        4.779477332387385e-14,
        -1.5619206968586225e-16,
    ],
};

// Objective (max u): value 1.5588061416067464e2, derivative 8.687771882940042e3.
pub(crate) const E_F64: Switch<f64, 7> = Switch {
    below: f64::from_bits(0x3fee_de82_0ba7_3310), // θ² < 9.646616199111993e-1
    series: [
        8.333333333333333e-3,
        -3.968253968253968e-4,
        8.267195767195768e-6,
        -1.0020843354176688e-7,
        8.029521918410807e-10,
        -4.58829823909189e-12,
        1.9680200780418645e-14,
    ],
};
