//! Check 3: every generated file is registered against the task that owns it and carries that
//! task's exact header (`docs/PHASE1.md` §3, §6). The regeneration comparison is each generator's
//! own `--check` (`thresholds --check`); this check owns the registry and the header. A file claims to be generated when one
//! of its first three lines is a comment leader followed by the marker, the shape `header_task`
//! parses; prose that mentions the marker, and another tool's `Cargo.lock` at any depth (its
//! marker is mid-sentence), are not claims.

use super::{File, Violation};

/// `(path, owning xtask task)`. A generator adds its output here in the PR that adds the generator.
const REGISTRY: &[(&str, &str)] = &[("xtask/src/seeded/generated.rs", "thresholds")];

pub(crate) fn check_registry(files: &[File]) -> Vec<Violation> {
    check(files, REGISTRY)
}

/// One valid file per registry entry, the header its task writes and nothing else: the fixtures of
/// the other checks add them so that the registry, which they do not test, stays silent.
#[cfg(test)]
pub(super) fn stubs() -> Vec<File> {
    let header = |task: &str| format!("// @generated by `cargo xtask {task}` — do not edit.\n");
    let stub = |&(path, task): &(&str, &str)| File::new(path, &header(task));
    REGISTRY.iter().map(stub).collect()
}

fn check(files: &[File], registry: &[(&str, &str)]) -> Vec<Violation> {
    let mut out = Vec::new();
    for f in files {
        let claimed = f
            .text
            .lines()
            .take(3)
            .position(|l| strip_leader(l).starts_with("@generated"));
        let owner = registry.iter().find(|(p, _)| *p == f.path).map(|&(_, t)| t);
        match (owner, claimed) {
            (Some(task), _) if header_task(&f.text) != Some(task) => out.push(Violation::new(
                &f.path,
                1,
                format!("[generated] must start with `@generated by `cargo xtask {task}``"),
            )),
            (None, Some(n)) => out.push(Violation::new(
                &f.path,
                n + 1,
                "[generated] `@generated` file is not in the xtask registry; register it with its task",
            )),
            _ => {}
        }
    }
    for (path, task) in registry {
        if !files.iter().any(|f| f.path == *path) {
            out.push(Violation::new(
                path,
                1,
                format!("[generated] registered output of `cargo xtask {task}` does not exist"),
            ));
        }
    }
    out
}

fn strip_leader(line: &str) -> &str {
    line.trim_start_matches(|c: char| c.is_whitespace() || "/!#*<-".contains(c))
}

/// The task named by a first line of the form: comment leader, marker, ``cargo xtask TASK``.
fn header_task(text: &str) -> Option<&str> {
    let rest = strip_leader(text.lines().next()?).strip_prefix("@generated by `cargo xtask ")?;
    rest.split_once('`')
        .map(|(task, _)| task)
        .filter(|t| !t.is_empty() && !t.contains(' '))
}

#[cfg(test)]
mod tests {
    use super::*;

    const REG: &[(&str, &str)] = &[("crates/x/gen.rs", "thresholds")];
    const HDR: &str =
        "// @generated by `cargo xtask thresholds` from a.csv — do not edit.\nfn f() {}\n";

    fn run(files: &[File]) -> Vec<String> {
        check(files, REG).iter().map(ToString::to_string).collect()
    }

    #[test]
    fn registered_file_with_header_passes() {
        assert!(run(&[File::new("crates/x/gen.rs", HDR)]).is_empty());
        let md = "<!-- @generated by `cargo xtask thresholds` -->\n";
        assert!(run(&[File::new("crates/x/gen.rs", md)]).is_empty());
        for lead in ["# ", "/* ", " * ", "//! ", "-- "] {
            let text = format!("{lead}@generated by `cargo xtask thresholds`\n");
            assert!(
                run(&[File::new("crates/x/gen.rs", &text)]).is_empty(),
                "{lead}"
            );
        }
    }

    #[test]
    fn registered_file_with_wrong_or_missing_header_fails() {
        for text in [
            "// header dropped\n",
            "\n// @generated by `cargo xtask thresholds`\n",
            "// @generated by `cargo xtask envelope`\n",
            "// @generated by cargo xtask thresholds\n",
            "// @generated by `cargo xtask `\n",
        ] {
            let v = run(&[File::new("crates/x/gen.rs", text)]);
            assert_eq!(v.len(), 1, "{text:?} -> {v:?}");
            assert!(v[0].starts_with("crates/x/gen.rs:1: "), "{v:?}");
        }
    }

    #[test]
    fn the_registry_names_the_seeded_switch_file_and_its_task() {
        assert_eq!(REGISTRY, [("xtask/src/seeded/generated.rs", "thresholds")]);
        // The header the generator writes, from its first line, is the one the check parses.
        let header = "// @generated by `cargo xtask thresholds` from conformance/sweeps/thresholds-seeded.csv — do not edit.\n";
        assert!(check_registry(&[File::new(REGISTRY[0].0, header)]).is_empty());
        assert_eq!(check_registry(&[]).len(), 1);
    }

    #[test]
    fn missing_registered_file_fails() {
        assert_eq!(run(&[]).len(), 1);
    }

    #[test]
    fn unregistered_generated_file_fails_within_three_lines_only() {
        let v = check(&[File::new("docs/E.md", "a\n\n<!-- @generated -->\n")], &[]);
        assert_eq!(v.len(), 1);
        assert!(v[0].to_string().starts_with("docs/E.md:3: "), "{v:?}");
        let late = File::new("docs/E.md", "a\nb\nc\n@generated\n");
        assert!(check(&[late], &[]).is_empty());
    }

    #[test]
    fn foreign_and_prose_mentions_are_not_claims() {
        let lock = "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\n";
        for path in ["Cargo.lock", "runners/tf_tree_math/Cargo.lock"] {
            assert!(check(&[File::new(path, lock)], &[]).is_empty(), "{path}");
        }
        let prose = File::new("docs/N.md", "# Notes on the @generated marker\n");
        assert!(check(&[prose], &[]).is_empty());
    }
}
